CREATE TABLE mails (
  id INT NOT NULL AUTO_INCREMENT,
  statement_type_item_id INT NOT NULL,
  user_id INT NOT NULL,
  ktp_file_path VARCHAR(100) NOT NULL UNIQUE,
  kk_file_path VARCHAR(100) NOT NULL UNIQUE,
  rt_rw_file_path VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (statement_type_item_id) REFERENCES statement_type_items(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE = InnoDB;